# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{octant}
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Anthony Williams"]
  s.date = %q{2010-06-27}
  s.description = %q{A framework-agnostic library for creating web-app navigation.}
  s.email = %q{hi@antw.me}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.md"
  ]
  s.files = [
    ".document",
     ".gitignore",
     ".rspec",
     ".yardoc/checksums",
     ".yardoc/objects/Octant.dat",
     ".yardoc/objects/Octant/Builders.dat",
     ".yardoc/objects/Octant/Builders/Item.dat",
     ".yardoc/objects/Octant/Builders/Item/initialize_i.dat",
     ".yardoc/objects/Octant/Builders/Item/item_i.dat",
     ".yardoc/objects/Octant/Builders/Item/title_i.dat",
     ".yardoc/objects/Octant/Builders/Item/url_i.dat",
     ".yardoc/objects/Octant/Builders/Navigation.dat",
     ".yardoc/objects/Octant/Builders/Navigation/add_i.dat",
     ".yardoc/objects/Octant/Builders/Navigation/build_i.dat",
     ".yardoc/objects/Octant/Builders/Navigation/initialize_i.dat",
     ".yardoc/objects/Octant/Formatters.dat",
     ".yardoc/objects/Octant/Formatters/Base.dat",
     ".yardoc/objects/Octant/Formatters/Base/html_link_i.dat",
     ".yardoc/objects/Octant/Formatters/Base/html_list_item_i.dat",
     ".yardoc/objects/Octant/Formatters/Base/initialize_i.dat",
     ".yardoc/objects/Octant/Formatters/Base/tag_i.dat",
     ".yardoc/objects/Octant/Formatters/Base/to_html_i.dat",
     ".yardoc/objects/Octant/Formatters/Base/trasform_item_to_html_i.dat",
     ".yardoc/objects/Octant/Item.dat",
     ".yardoc/objects/Octant/Item/guard_3D_i.dat",
     ".yardoc/objects/Octant/Item/guard_i.dat",
     ".yardoc/objects/Octant/Item/initialize_i.dat",
     ".yardoc/objects/Octant/Item/label_i.dat",
     ".yardoc/objects/Octant/Item/name_i.dat",
     ".yardoc/objects/Octant/Item/resource_3D_i.dat",
     ".yardoc/objects/Octant/Item/resource_i.dat",
     ".yardoc/objects/Octant/Item/title_3D_i.dat",
     ".yardoc/objects/Octant/Item/title_i.dat",
     ".yardoc/objects/Octant/Item/url_3D_i.dat",
     ".yardoc/objects/Octant/Item/url_i.dat",
     ".yardoc/objects/Octant/Navigation.dat",
     ".yardoc/objects/Octant/Navigation/initialize_i.dat",
     ".yardoc/objects/Octant/Navigation/items_i.dat",
     ".yardoc/objects/Octant/Navigation/name_i.dat",
     ".yardoc/objects/Octant/VERSION.dat",
     ".yardoc/objects/Octant/get_i.dat",
     ".yardoc/objects/Octant/reset_21_i.dat",
     ".yardoc/objects/Octant/setup_i.dat",
     ".yardoc/objects/root.dat",
     ".yardoc/proxy_types",
     "LICENSE",
     "README.md",
     "Rakefile",
     "VERSION",
     "doc/Octant.html",
     "doc/Octant/Builders.html",
     "doc/Octant/Builders/Item.html",
     "doc/Octant/Builders/Navigation.html",
     "doc/Octant/Formatters.html",
     "doc/Octant/Formatters/Base.html",
     "doc/Octant/Item.html",
     "doc/Octant/Navigation.html",
     "doc/_index.html",
     "doc/class_list.html",
     "doc/css/common.css",
     "doc/css/full_list.css",
     "doc/css/style.css",
     "doc/file.README.html",
     "doc/file_list.html",
     "doc/frames.html",
     "doc/index.html",
     "doc/js/app.js",
     "doc/js/full_list.js",
     "doc/js/jquery.js",
     "doc/method_list.html",
     "doc/top-level-namespace.html",
     "features/active_items.feature",
     "features/content_injection.feature",
     "features/guard_conditions.feature",
     "features/html5_formatter.feature",
     "features/static_url.feature",
     "features/step_definitions/octant_steps.rb",
     "features/support/env.rb",
     "features/title.feature",
     "lib/octant.rb",
     "lib/octant/builders.rb",
     "lib/octant/builders/item.rb",
     "lib/octant/builders/navigation.rb",
     "lib/octant/formatters.rb",
     "lib/octant/formatters/base.rb",
     "lib/octant/formatters/html5.rb",
     "lib/octant/item.rb",
     "lib/octant/item_matcher.rb",
     "lib/octant/navigation.rb",
     "lib/octant/version.rb",
     "spec/octant/builders_spec.rb",
     "spec/octant/item_matcher_spec.rb",
     "spec/octant/item_spec.rb",
     "spec/octant/navigation_spec.rb",
     "spec/spec_helper.rb",
     "spec/support/blueprints.rb",
     "tasks/features.rake",
     "tasks/spec.rake",
     "tasks/yard.rake"
  ]
  s.has_rdoc = false
  s.homepage = %q{http://github.com/antw/octant}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Octant}
  s.test_files = [
    "spec/octant/builders_spec.rb",
     "spec/octant/item_matcher_spec.rb",
     "spec/octant/item_spec.rb",
     "spec/octant/navigation_spec.rb",
     "spec/spec_helper.rb",
     "spec/support/blueprints.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec-core>, [">= 2.0.0.beta.12"])
      s.add_development_dependency(%q<rspec-expectations>, [">= 2.0.0.beta.12"])
      s.add_development_dependency(%q<rspec-mocks>, [">= 2.0.0.beta.12"])
      s.add_development_dependency(%q<cucumber>, [">= 0.8"])
      s.add_development_dependency(%q<nokogiri>, [">= 1.4"])
      s.add_development_dependency(%q<webrat>, [">= 0.7"])
      s.add_development_dependency(%q<yard>, [">= 0.5"])
    else
      s.add_dependency(%q<rspec-core>, [">= 2.0.0.beta.12"])
      s.add_dependency(%q<rspec-expectations>, [">= 2.0.0.beta.12"])
      s.add_dependency(%q<rspec-mocks>, [">= 2.0.0.beta.12"])
      s.add_dependency(%q<cucumber>, [">= 0.8"])
      s.add_dependency(%q<nokogiri>, [">= 1.4"])
      s.add_dependency(%q<webrat>, [">= 0.7"])
      s.add_dependency(%q<yard>, [">= 0.5"])
    end
  else
    s.add_dependency(%q<rspec-core>, [">= 2.0.0.beta.12"])
    s.add_dependency(%q<rspec-expectations>, [">= 2.0.0.beta.12"])
    s.add_dependency(%q<rspec-mocks>, [">= 2.0.0.beta.12"])
    s.add_dependency(%q<cucumber>, [">= 0.8"])
    s.add_dependency(%q<nokogiri>, [">= 1.4"])
    s.add_dependency(%q<webrat>, [">= 0.7"])
    s.add_dependency(%q<yard>, [">= 0.5"])
  end
end

